// Re-export new RTK slice actions for backward compatibility
export {
  getProductList,
  createAndSaveProduct,
  createWarehouse,
  getProductWareHouseList,
  getProductVatCategoryList,
  getExciseTaxList,
  getTransactionCategoryListForInventory,
  getProductCategoryList,
  removeBulk,
  getInventoryByProductId,
  getInventoryHistory,
  getTransactionCategoryListForSalesProduct,
  getTransactionCategoryListForPurchaseProduct,
  checkValidation,
  checkProductNameValidation,
  getInvoicesCountProduct,
  getInventoryById,
  updateInventory,
  getProductCode,
  getProductCodePrefix,
  getCompanyDetails,
  getUnitTypeList,
  setProductList,
  setVatList,
  setProductWarehouseList,
  setProductCategoryList,
  setInventoryAccountList,
  setInventoryList,
  setInventoryHistoryList,
  clearError,
} from './productSlice';
