import { combineReducers } from 'redux';

// Import new RTK slices
import authReducer from './global/auth/authSlice';
import commonReducer from './global/common/commonSlice';

// Import screen module objects (not lazy-loaded) for reducer access
import {
  Dashboard,
  Journal,
  BankAccount,
  Employee,
  Contact,
  Expense,
  GeneralSettings,
  CustomerInvoice,
  Receipt,
  SupplierInvoice,
  Product,
  Project,
  Payment,
  TransactionCategory,
  User,
  VatCode,
  Currency,
  CurrencyConvert,
  Help,
  Notification,
  Organization,
  UsersRoles,
  DataBackup,
  TransactionsReport,
  ChartAccount,
  ProductCategory,
  Profile,
  ImportTransaction,
  OpeningBalance,
  VatTransactions,
  Inventory,
  Quotation,
  RequestForQuotation,
  PurchaseOrder,
  GoodsReceivedNote,
  FinancialReport,
  SalaryRoles,
  SalaryStucture,
  SalaryTemplate,
  Designation,
  PayrollEmployee,
  CreditNotes,
  Import,
  PayrollRun,
  DebitNotes,
} from 'screens/reducers';

import InvoiceViewJournalReducer from 'components/invoice_view_journal_entries/invoiceViewJournalSlice';

// Helper function to safely get reducer (returns identity function if reducer is undefined)
const getReducer = (module) => {
  return module?.reducer || ((state = null) => state);
};

const reducer = combineReducers({
  common: commonReducer,
  auth: authReducer,

  dashboard: getReducer(Dashboard),
  journal: getReducer(Journal),
  bank_account: getReducer(BankAccount),
  employee: getReducer(Employee),
  contact: getReducer(Contact),
  expense: getReducer(Expense),
  settings: getReducer(GeneralSettings),
  customer_invoice: getReducer(CustomerInvoice),
  vat_transactions: getReducer(VatTransactions),
  receipt: getReducer(Receipt),
  supplier_invoice: getReducer(SupplierInvoice),
  debit_notes: getReducer(DebitNotes),
  request_for_quotation: getReducer(RequestForQuotation),
  purchase_order: getReducer(PurchaseOrder),
  goods_received_note: getReducer(GoodsReceivedNote),
  quotation: getReducer(Quotation),
  product: getReducer(Product),
  project: getReducer(Project),
  payment: getReducer(Payment),
  transaction: getReducer(TransactionCategory),
  currencyConvert: getReducer(CurrencyConvert),
  vat: getReducer(VatCode),
  currency: getReducer(Currency),
  help: getReducer(Help),
  reports: getReducer(FinancialReport),
  notification: getReducer(Notification),
  organization: getReducer(Organization),
  users_roles: getReducer(UsersRoles),
  data_backup: getReducer(DataBackup),
  transaction_data: getReducer(TransactionsReport),
  chart_account: getReducer(ChartAccount),
  product_category: getReducer(ProductCategory),
  profile: getReducer(Profile),
  import_transaction: getReducer(ImportTransaction),
  opening_balance: getReducer(OpeningBalance),
  inventory: getReducer(Inventory),
  salaryRoles: getReducer(SalaryRoles),
  salaryStructure: getReducer(SalaryStucture),
  salarytemplate: getReducer(SalaryTemplate),
  employeeDesignation: getReducer(Designation),
  payrollEmployee: getReducer(PayrollEmployee),
  user: getReducer(User),
  creditNote: getReducer(CreditNotes),
  payrollRun: getReducer(PayrollRun),
  import: getReducer(Import),
  invoice_view_journal: InvoiceViewJournalReducer,
});

export default reducer;
