DROP TABLE IF EXISTS SALARY_ROLE;
DROP SEQUENCE IF EXISTS SALARY_ROLE_SEQ;

CREATE SEQUENCE SALARY_ROLE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SALARY_ROLE (
    SALARY_ROLE_ID INTEGER PRIMARY KEY,
    ROLE_NAME VARCHAR(255),
    DELETE_FLAG BOOLEAN NOT NULL,
    ORDER_SEQUENCE INTEGER,
    CREATED_BY INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATE_DATE TIMESTAMP,
    VERSION_NUMBER INTEGER NOT NULL
);
