DROP TABLE IF EXISTS EMPLOYEE_SALARY_COMPONENT_RELATION;
DROP TABLE IF EXISTS SALARY_TEMPLATE;
DROP TABLE IF EXISTS SALARY_COMPONENT;
DROP TABLE IF EXISTS SALARY_STRUCTURE;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS SALARY_ROLE;

DROP SEQUENCE IF EXISTS EMPLOYEE_SALARY_COMPONENT_RELATION_SEQ;
DROP SEQUENCE IF EXISTS SALARY_TEMPLATE_SEQ;
DROP SEQUENCE IF EXISTS SALARY_COMPONENT_SEQ;
DROP SEQUENCE IF EXISTS SALARY_STRUCTURE_SEQ;
DROP SEQUENCE IF EXISTS EMPLOYEE_SEQ;
DROP SEQUENCE IF EXISTS SALARY_ROLE_SEQ;

CREATE SEQUENCE SALARY_ROLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SALARY_STRUCTURE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SALARY_COMPONENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EMPLOYEE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EMPLOYEE_SALARY_COMPONENT_RELATION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SALARY_TEMPLATE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SALARY_ROLE (
    SALARY_ROLE_ID INTEGER PRIMARY KEY,
    ROLE_NAME VARCHAR(255),
    DELETE_FLAG BOOLEAN NOT NULL,
    ORDER_SEQUENCE INTEGER,
    CREATED_BY INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATE_DATE TIMESTAMP,
    VERSION_NUMBER INTEGER NOT NULL
);

CREATE TABLE SALARY_STRUCTURE (
    SALARY_STRUCTURE_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255),
    TYPE VARCHAR(50),
    ORDER_SEQUENCE INTEGER,
    CREATED_BY INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATE_DATE TIMESTAMP,
    DELETE_FLAG BOOLEAN NOT NULL,
    VERSION_NUMBER INTEGER NOT NULL
);

CREATE TABLE SALARY_COMPONENT (
    SALARY_COMPONENT_ID INTEGER PRIMARY KEY,
    SALARY_STRUCTURE_ID INTEGER,
    DESCRIPTION VARCHAR(255),
    FORMULA VARCHAR(255),
    FLAT_AMOUNT VARCHAR(255),
    DELETE_FLAG BOOLEAN NOT NULL,
    IS_EDITABLE BOOLEAN NOT NULL,
    ORDER_SEQUENCE INTEGER,
    CREATED_BY INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATE_DATE TIMESTAMP,
    VERSION_NUMBER INTEGER NOT NULL,
    CALCULATION_TYPE INTEGER,
    COMPONENT_TYPE VARCHAR(50),
    COMPONENT_CODE VARCHAR(50),
    CONSTRAINT FK_SALARY_COMPONENT_STRUCTURE FOREIGN KEY (SALARY_STRUCTURE_ID)
        REFERENCES SALARY_STRUCTURE (SALARY_STRUCTURE_ID)
);

CREATE TABLE SALARY_TEMPLATE (
    SALARY_TEMPLATE_ID INTEGER PRIMARY KEY,
    SALARY_COMPONENT_ID INTEGER,
    SALARY_ROLE_ID INTEGER,
    IS_ACTIVE BOOLEAN,
    IS_EDITABLE BOOLEAN NOT NULL,
    ORDER_SEQUENCE INTEGER,
    CREATED_BY INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATE_DATE TIMESTAMP,
    DELETE_FLAG BOOLEAN NOT NULL,
    VERSION_NUMBER INTEGER NOT NULL,
    CONSTRAINT FK_SALARY_TEMPLATE_COMPONENT FOREIGN KEY (SALARY_COMPONENT_ID)
        REFERENCES SALARY_COMPONENT (SALARY_COMPONENT_ID),
    CONSTRAINT FK_SALARY_TEMPLATE_ROLE FOREIGN KEY (SALARY_ROLE_ID)
        REFERENCES SALARY_ROLE (SALARY_ROLE_ID)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER,
    FIRST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DATE_OF_BIRTH TIMESTAMP,
    EMAIL VARCHAR(255),
    PRESENT_ADDRESS VARCHAR(255),
    PROFILE_IMAGE BLOB,
    PERMANENT_ADDRESS VARCHAR(255),
    COUNTRY_CODE INTEGER,
    STATE_ID INTEGER,
    CITY VARCHAR(255),
    PIN_CODE INTEGER,
    HOME_ADDRESS VARCHAR(255),
    EMERGENCY_CONTACT_NAME_1 VARCHAR(255),
    EMERGENCY_CONTACT_NUMBER_1 VARCHAR(255),
    EMERGENCY_CONTACT_RELATIONSHIP_1 VARCHAR(255),
    EMERGENCY_CONTACT_NAME_2 VARCHAR(255),
    EMERGENCY_CONTACT_NUMBER_2 VARCHAR(255),
    EMERGENCY_CONTACT_RELATIONSHIP_2 VARCHAR(255),
    UNIVERSITY VARCHAR(255),
    QUALIFICATION VARCHAR(255),
    QUALIFICATION_YEAR_OF_COMPLETIONDATE VARCHAR(255),
    GENDER VARCHAR(50),
    MOBILE_NUMBER VARCHAR(100),
    BLOOD_GROUP VARCHAR(50),
    MARITAL_STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    CREATED_BY INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATE_DATE TIMESTAMP,
    DELETE_FLAG BOOLEAN NOT NULL,
    EMPLOYEE_DESIGNATION_ID INTEGER,
    SALARY_ROLE_ID INTEGER,
    TRANSACTION_CATEGORY_CODE INTEGER,
    VERSION_NUMBER INTEGER NOT NULL
);

CREATE TABLE EMPLOYEE_SALARY_COMPONENT_RELATION (
    EMPLOYEE_SALARY_COMPONENT_RELATION_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID INTEGER,
    SALARY_COMPONENT_ID INTEGER,
    SALARY_STRUCTURE_ID INTEGER,
    DESCRIPTION VARCHAR(255),
    FORMULA VARCHAR(255),
    NO_OF_DAYS DECIMAL(19,2),
    FLAT_AMOUNT VARCHAR(255),
    MONTHLY_AMOUNT DECIMAL(19,2),
    YEARLY_AMOUNT DECIMAL(19,2),
    DELETE_FLAG BOOLEAN NOT NULL,
    ORDER_SEQUENCE INTEGER,
    CREATED_BY INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATE_DATE TIMESTAMP,
    VERSION_NUMBER INTEGER NOT NULL,
    CONSTRAINT FK_ESC_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
    CONSTRAINT FK_ESC_COMPONENT FOREIGN KEY (SALARY_COMPONENT_ID) REFERENCES SALARY_COMPONENT (SALARY_COMPONENT_ID),
    CONSTRAINT FK_ESC_STRUCTURE FOREIGN KEY (SALARY_STRUCTURE_ID) REFERENCES SALARY_STRUCTURE (SALARY_STRUCTURE_ID)
);
